services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 80:80
    depends_on:
      - backend
  backend:
    container_name: backend
    restart: always
    command: node ./dist/main.mjs
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
